// Draws the sample pets' invented avatar illustrations and writes them as WebP data URLs to
// src/lib/demoPhotos.ts. No real photos: flat shapes only. Run: bun scripts/demo-photos.ts
import sharp from 'sharp';
import { writeFileSync } from 'node:fs';

/** Biscuit: a beagle, tan and white with long brown ears, on a sage background. */
const biscuit = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">
  <rect width="256" height="256" fill="#c9d6c4"/>
  <ellipse cx="128" cy="250" rx="96" ry="54" fill="#f4efe6"/>
  <path d="M60 104 C40 120 34 176 52 198 C66 214 84 196 86 170 L92 116 Z" fill="#7a4a2a"/>
  <path d="M196 104 C216 120 222 176 204 198 C190 214 172 196 170 170 L164 116 Z" fill="#7a4a2a"/>
  <ellipse cx="128" cy="124" rx="56" ry="60" fill="#c98a4b"/>
  <path d="M116 70 C120 100 116 140 106 168 L150 168 C140 140 136 100 140 70 Z" fill="#f4efe6"/>
  <ellipse cx="128" cy="174" rx="40" ry="30" fill="#f4efe6"/>
  <circle cx="104" cy="120" r="8" fill="#2b2118"/>
  <circle cx="152" cy="120" r="8" fill="#2b2118"/>
  <circle cx="106" cy="117" r="2.5" fill="#ffffff"/>
  <circle cx="154" cy="117" r="2.5" fill="#ffffff"/>
  <ellipse cx="128" cy="158" rx="13" ry="9" fill="#2b2118"/>
  <path d="M128 167 L128 178 M116 182 Q128 192 140 182" stroke="#2b2118" stroke-width="4" fill="none" stroke-linecap="round"/>
  <path d="M132 186 Q136 200 128 202 Q120 200 124 186 Z" fill="#d9776a"/>
</svg>`;

/** Miso: a grey tabby cat with green eyes, on a pale blue background. */
const miso = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">
  <rect width="256" height="256" fill="#c7d3df"/>
  <ellipse cx="128" cy="252" rx="92" ry="52" fill="#8d8f94"/>
  <path d="M70 120 L66 46 L118 86 Z" fill="#8d8f94"/>
  <path d="M186 120 L190 46 L138 86 Z" fill="#8d8f94"/>
  <path d="M78 104 L76 62 L106 86 Z" fill="#e6b7b0"/>
  <path d="M178 104 L180 62 L150 86 Z" fill="#e6b7b0"/>
  <ellipse cx="128" cy="140" rx="70" ry="62" fill="#9a9ca1"/>
  <path d="M128 80 L128 104 M110 82 L114 102 M146 82 L142 102" stroke="#5f6166" stroke-width="6" stroke-linecap="round"/>
  <path d="M62 140 L86 144 M62 160 L86 156 M194 140 L170 144 M194 160 L170 156" stroke="#5f6166" stroke-width="5" stroke-linecap="round"/>
  <ellipse cx="128" cy="170" rx="34" ry="24" fill="#e9e6e1"/>
  <ellipse cx="100" cy="134" rx="13" ry="14" fill="#9cc27a"/>
  <ellipse cx="156" cy="134" rx="13" ry="14" fill="#9cc27a"/>
  <ellipse cx="100" cy="134" rx="4" ry="11" fill="#1f2a1a"/>
  <ellipse cx="156" cy="134" rx="4" ry="11" fill="#1f2a1a"/>
  <path d="M120 158 L136 158 L128 167 Z" fill="#d98c8c"/>
  <path d="M128 167 L128 174 M128 174 Q120 182 112 176 M128 174 Q136 182 144 176" stroke="#5f6166" stroke-width="3" fill="none" stroke-linecap="round"/>
  <path d="M94 168 L56 162 M94 174 L58 180 M162 168 L200 162 M162 174 L198 180" stroke="#f4f2ee" stroke-width="2" stroke-linecap="round"/>
</svg>`;

const toDataUrl = async (svg: string) => `data:image/webp;base64,${(await sharp(Buffer.from(svg)).resize(256, 256).webp({ quality: 80 }).toBuffer()).toString('base64')}`;

const [b, m] = await Promise.all([toDataUrl(biscuit), toDataUrl(miso)]);
writeFileSync(
  new URL('../src/lib/demoPhotos.ts', import.meta.url),
  `// Generated by scripts/demo-photos.ts: invented illustrations of the sample pets, not photos.\n\n/** WebP data URLs by sample pet id. */\nexport const DEMO_PHOTOS: Record<string, string> = {\n  'demo-pet-biscuit': '${b}',\n  'demo-pet-miso': '${m}',\n};\n`,
);
console.log(`biscuit ${b.length} chars, miso ${m.length} chars`);
